### ISSUE TITLE
Osmosis frontend throws an error which takes over the entire page (frontend is unusable)

### ISSUE THREAD

**Issue by gmakestyle** [osmosis-labs/osmosis-frontend#1262]
Browser shows a white screen (side + top panels work) with:
Application error: a client-side exception has occurred (see the browser console for more information).

The console logs show:

RangeError: Division by zero
    at l.over.l.divide (_app-8d1557485e9147d2.js:1:1963682)
    at u.quoRaw (_app-8d1557485e9147d2.js:1:1712787)
    at u.quo (_app-8d1557485e9147d2.js:1:1712479)
    at a.quo (_app-8d1557485e9147d2.js:1:1717906)
    at s.quo (_app-8d1557485e9147d2.js:1:1705820)
    at _app-8d1557485e9147d2.js:1:5781196
    at Array.forEach (<anonymous>)
    at _app-8d1557485e9147d2.js:1:5781113
    at Array.map (<anonymous>)

    at get bondDurations (_app-8d1557485e9147d2.js:1:5780307)
    
 Reproducible in Chrome on two different machines (one Linux, one Mac) have not tried a different browser. Started first getting this error ~10 minutes ago, was using Osmosis fine before that.

<img width="1408" alt="Screen Shot 2023-01-26 at 18 23 47" src="https://user-images.githubusercontent.com/4348446/214800729-194eca39-f6d4-4d10-b089-4974db26c080.png">

**Comment by jonator** [comment]
We noticed and just fixed this. Thanks!
